/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        // Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "Alpro", "A"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "Strukdat", "B"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "BasDat", "C"));
        // Set Table
        tableOutput.setModel(setTable());
        // Hide Delete button
        btnDelete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = { "NIM", "Nama", "Mata Kuliah", "Nilai" };
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[4];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getMatkul();
            row[3] = listMhs.get(i).getNilai();

            dataTabel.addRow(row);
        }

        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = txtFieldNIM.getText();
        String nama = txtFieldName.getText();
        String matkul = txtFieldMatkul.getText();
        String nilai = txtFieldNilai.getText();

        if (nim.length() == 0 || nama.length() == 0 || nilai.length() == 0 || matkul.length() == 0) {
            JOptionPane.showMessageDialog(null, "Input Tidak Lengkap");
            txtFieldNIM.setText("");
            txtFieldName.setText("");
            txtFieldMatkul.setText("");
            txtFieldNilai.setText("");
        } else {
            listMhs.add(new Mahasiswa(nim, nama, matkul, nilai));
            // Update Table
            tableOutput.setModel(setTable());

            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            txtFieldNIM.setText("");
            txtFieldName.setText("");
            txtFieldMatkul.setText("");
            txtFieldNilai.setText("");
        }

    }

    public void updateData() {

        // Get Data
        String nim = txtFieldNIM.getText();
        String nama = txtFieldName.getText();
        String matkul = txtFieldMatkul.getText();
        String nilai = txtFieldNilai.getText();
        // System.out.println(nim + nama + nilai);
        if (nim.length() == 0 || nama.length() == 0 || nilai.length() == 0 || matkul.length() == 0) {
            JOptionPane.showMessageDialog(null, "Input Tidak Lengkap");
            txtFieldNIM.setText("");
            txtFieldName.setText("");
            txtFieldMatkul.setText("");
            txtFieldNilai.setText("");
        } else {
            listMhs.get(selectedID).setNim(nim);
            listMhs.get(selectedID).setNama(nama);
            listMhs.get(selectedID).setMatkul(matkul);
            listMhs.get(selectedID).setNilai(nilai);

            // Update Table
            tableOutput.setModel(setTable());
            System.out.println("Update Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            txtFieldNIM.setText("");
            txtFieldName.setText("");
            txtFieldMatkul.setText("");
            txtFieldNilai.setText("");
        }
    }

    public void deleteData() {
        listMhs.remove(selectedID);
        // Update Table
        tableOutput.setModel(setTable());
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        txtFieldNIM.setText("");
        txtFieldName.setText("");
        txtFieldMatkul.setText("");
        txtFieldNilai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDaftarMahasiswa = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtFieldNIM = new javax.swing.JTextField();
        lblNIM = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        lblNilai = new javax.swing.JLabel();
        txtFieldNilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOutput = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtFieldMatkul = new javax.swing.JTextField();
        lblMatkul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDaftarMahasiswa.setFont(new java.awt.Font("Arial Black", 0, 26)); // NOI18N
        lblDaftarMahasiswa.setText("Daftar Mahasiswa");

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNIMActionPerformed(evt);
            }
        });

        lblNIM.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNIM.setText("NIM");

        lblName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblName.setText("Nama");

        txtFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNameActionPerformed(evt);
            }
        });

        lblNilai.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNilai.setText("Nilai");

        txtFieldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNilaiActionPerformed(evt);
            }
        });

        tableOutput.setAutoCreateRowSorter(true);
        tableOutput.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        tableOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableOutput.setUpdateSelectionOnSort(false);
        tableOutput.setVerifyInputWhenFocusTarget(false);
        tableOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOutputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOutput);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtFieldMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldMatkulActionPerformed(evt);
            }
        });

        lblMatkul.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblMatkul.setText("MatKul");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lblName)
                                                                                        .addComponent(lblNIM))
                                                                                .addGap(28, 28, 28)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(txtFieldName,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                197,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(txtFieldNIM,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                197,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(lblNilai)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(txtFieldNilai,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        197,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(lblMatkul)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(txtFieldMatkul,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        197,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnAdd)
                                                                        .addComponent(btnDelete)
                                                                        .addComponent(btnCancel)))
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(144, 144, 144)
                                                .addComponent(lblDaftarMahasiswa)))
                                .addContainerGap(84, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblDaftarMahasiswa)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAdd)
                                        .addComponent(lblNIM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel)
                                        .addComponent(lblName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDelete)
                                        .addComponent(txtFieldMatkul, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMatkul))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNilai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40,
                                        Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldNIMActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldNIMActionPerformed

    private void txtFieldNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldNameActionPerformed

    private void txtFieldNilaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldNilaiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldNilaiActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false)
            insertData();
        else {
            updateData();
            btnAdd.setText("Add");
            btnDelete.setVisible(false);
            this.isUpdate = false;
        }
    }// GEN-LAST:event_btnAddActionPerformed

    private void tableOutputMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableOutputMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        // Get Selected Data
        int row = tableOutput.getSelectedRow();
        String selectedNim = (tableOutput.getModel().getValueAt(row, 0).toString());
        String selectedNama = (tableOutput.getModel().getValueAt(row, 1).toString());
        String selectedMatkul = (tableOutput.getModel().getValueAt(row, 2).toString());
        String selectedNilai = (tableOutput.getModel().getValueAt(row, 3).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        // System.out.println(selectedID);
        txtFieldNIM.setText(selectedNim);
        txtFieldName.setText(selectedNama);
        txtFieldMatkul.setText(selectedMatkul);
        txtFieldNilai.setText(selectedNilai);

        btnAdd.setText("Update");
        btnDelete.setVisible(true);
    }// GEN-LAST:event_tableOutputMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            btnAdd.setText("Add");
            btnDelete.setVisible(false);
            this.isUpdate = false;
        }
    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtFieldNIM.setText("");
        txtFieldName.setText("");
        txtFieldMatkul.setText("");
        txtFieldNilai.setText("");
        btnAdd.setText("Add");
        btnDelete.setVisible(false);
        this.isUpdate = false;
    }// GEN-LAST:event_btnCancelActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnAddMouseClicked

    private void txtFieldMatkulActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldMatkulActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDaftarMahasiswa;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JTable tableOutput;
    private javax.swing.JTextField txtFieldMatkul;
    private javax.swing.JTextField txtFieldNIM;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldNilai;
    // End of variables declaration//GEN-END:variables
}
